# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploaded_photos'),
            preserve_default=False,
        ),
    ]
